version: '3'
services:
  db:
    image: postgres:12.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=example
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

    volumes:
      - .:/myapp
      - /myapp/node_modules

    ports:
      - "3000:3000"

    environment:
      - POSTGRES_PASSWORD=example
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=webpacker

    depends_on:
      - db
      - webpacker

  webpacker:
    build: .
    environment: 
      - NODE_ENV=development
      - RAILS_ENV=development
      - WEBPACKER_DEV_SERVER_HOST=0.0.0.0
    # hot module replacement & port set to 3035 & bind host to 0.0.0.0
    command: ./bin/webpack-dev-server
    volumes:
      - .:/webpacker
    ports:
      - "3035:3035"

