version: '3'
services:
  db:
    image: postgres:12.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"

    volumes:
      - .:/myapp
      - /myapp/node_modules

    ports:
      - "3000:3000"

    environment:
      - RAILS_ENV=development

    depends_on:
      - db
      - webpacker

  webpacker:
    build: .
    # hot module replacement & port set to 3035 & bind host to 0.0.0.0
    command: bash -c "./bin/webpack-dev-server --mode development --hot --port 3035 --host 0.0.0.0"
    ports:
      - 3035:3035

