version: '3'
services:
  db:
    image: postgres:12.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file:
      - ./.env
  web:
    env_file:
      - ./.env

    build:
      context: .
      args:
        GROUP_ID: ${GROUP_ID:-0}
        USER_ID: ${USER_ID:-0}

        command: bash -c "chown ${USER_ID:-0}:${GROUP_ID:-0} /var/lib/postgresql/data && \
                          rm -f tmp/pids/server.pid && \
                          bundle exec rails server -p 3000 -b '0.0.0.0'"

    volumes:
      - .:/myapp
      - /myapp/node_modules
    tmpfs:
      - /myapp/tmp/

    ports:
      - "3000:3000"

    depends_on:
      - db
      - webpacker

  webpacker:
    env_file:
      - ./.env

    build:
      context: .
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}

    command: "./bin/webpack-dev-server --hot --port 3035"
    volumes:
      - .:/myapp
    ports:
      - "3035:3035"
