version: '3'
services:
  db:
    env_file:
      - ./.env
    image: postgres:12.2
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    env_file:
      - ./.env
    user: ${USER_ID:-1000}:${GROUP_ID:-1000}
    build:
      context: .
      args:
        GROUP_ID: ${GROUP_ID:-1000}
        USER_ID: ${USER_ID:-1000}

    command: bash -c "rm -f tmp/pids/server.pid &&
                      ./bin/webpack-dev-server --hot --port 3035 &
                      bundle exec rails server -p 3000 -b '0.0.0.0'"
    volumes:
      - .:${APP_DIR}

    ports:
      - "3000:3000"
      - "3035:3035"

    depends_on:
      - db
